### PR TITLE
fix(core): switch to npx to fix firebase command path on windows

### PR DESCRIPTION
**Pull request by dhair-seva**
Since this is a simple fix, I was able to make this PR. This is to go to npx for run firebase. This should fix https://github.com/prescottprue/cypress-firebase/issues/68

### CODE REVIEW

**Comment by prescottprue** [comment]
Thanks for the PR! I was considering switching it to use npx just in the case that it is windows so it is not breaking for folks using versions of node with npx not included. That said, using npx may be the better way moving forward, so I’ll merge this after a little more research

**Comment by dhair-seva** [comment]
Sounds good! I'm pushing up a fix for the failed build. For some reason, I didn't realize that you were using yarn in your project. Removing the package-lock and updating it with yarn

**Comment by dhair-seva** [comment]
I think this PR is ready to go. Is there anything else that needs to be done for this to be merged?

**Comment by prescottprue** [comment]
Released in [`v0.6.0-alpha`](https://github.com/prescottprue/cypress-firebase/releases/tag/v0.6.0-alpha) - going to confirm which versions it will be breaking for before getting it out to latest

**Pull request merged**
